apiVersion: batch/v1
kind: CronJob
metadata:
  name: jobcron
spec: 
  schedule: '* * * * *'
  jobTemplate: 
    metadata:
      name: hellocronjob
    spec: 
      template: 
        metadata: 
          name: livedatapod
        spec:
          restartPolicy: Never 
          containers:
            - name: nginx
              image: nginx
              ports:
                - containerPort: 80 
                
