apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  template:
    metadata:
      name: hellopod
    spec:
      restartPolicy: "Never"
      containers:
        - image: alpine:latest
          name: alpine
          command:
            - sleep
            - 1d
       
