apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  template:
    metadata:
      name: hellopod
    spec:
      restartPolicy: OnFailure
      containers:
        - image: alpine
          name: alpine
-
  
          

         
       
