apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: jenkins-rs
spec: 
  minReadySeconds: 3
  replicas: 4
  selector: 
    matchLabels: 
      app: jenkins  
  template: 
    metadata:
      name: jenkins
      labels: 
        app: jenkins
    spec: 
      containers:
        - name: jenkins 
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080   
              