apiVersion: v1
kind: Pod
metadata: 
  name: config
spec: 
  containers:
    - name: mysql
      image: mysql
      ports: 
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: mysql-secret
            optional: false

        
        


      
      