apiVersion: v1
kind: Pod
metadata: 
  name: alpine-file
spec:
  containers:
    - name: alpine
      image: alpine
      args: 
        - sleep
        - 1d
      volumeMounts:
        - name: donut
          mountPath: /tmp/donut
  volumes:
    - name: donut
      configMap:
        name: dummy         
